[terminal]
shell = { program = "/usr/bin/fish", args = ["--login"] }

[font]
normal = {family = "RobotoMonoNerdFont", style = "Regular"}
size = 16

[window]
opacity = 0.2
blur = true

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true
