[terminal]
shell = { program = "/usr/bin/fish", args = ["--login"] }

[font]
normal = {family = "RobotoMonoNerdFont", style = "Regular"}
size = 16

[window]
padding = { x = 15, y = 0 }
opacity = 0
blur = false

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[env]
TERM = "xterm-256color"

[colors.primary]
background = "#002635"  # bg
foreground = "#e6e6dc"  # fg

[colors.normal]
black   = "#517f8d"     # grey (used as base black / muted)
red     = "#ff5a67"     # red
green   = "#7fc06e"     # green
yellow  = "#ffcc1b"     # yellow
blue    = "#12ade0"     # blue
magenta = "#c694ff"     # magenta (from pink)
cyan    = "#00ffff"     # cyan_light
white   = "#b7cff9"     # purple (used as soft white)

[colors.bright]
black   = "#517f8d"     # same as normal.black
red     = "#ff5a67"     # same as normal.red
green   = "#7fc06e"     # same as normal.green
yellow  = "#ffcc1b"     # same as normal.yellow
blue    = "#12ade0"     # same as normal.blue
magenta = "#c694ff"     # same as normal.magenta
cyan    = "#00ffff"     # same as normal.cyan
white   = "#b7cff9"     # same as normal.white

